num_epochs: 1
batch_size: 16
learning_rate: 0.0001
resume: false
checkpoint: null
start_epoch: 1
exp_name: training
batch_every: 1
save_every: 10
epoch_every: 1
shuffle: true
train_dataset_path: datasets/cat_train
test_dataset_path: datasets/cat_test
num_workers: 2
model_cls: CAEC_16_8_8
